version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6

executors:
  default:
    docker:
      - image: cimg/ruby:3.2.0-node # ✅ NodeとYarn同梱
    working_directory: ~/app

jobs:
  build_test:
    docker:
      - image: cimg/ruby:3.2.0-node
      - image: cimg/postgres:14.9
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: app_test
          POSTGRES_PASSWORD: password
    steps:
      - checkout

      - run:
          name: Install system dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y libvips

      - run:
          name: Install Ruby gems
          command: |
            gem install bundler
            bundle install --jobs=4 --retry=3

      - run:
          name: Yarn install
          command: yarn install --check-files

      - run:
          name: Setup DB
          command: |
            cp config/database.yml.ci config/database.yml || echo "No custom DB config"
            bundle exec rails db:create db:schema:load

      - run:
          name: Install Chrome 122 & matching ChromeDriver
          command: |
            sudo apt-get update
            sudo apt-get install -y wget unzip curl fonts-liberation libappindicator3-1 libasound2

            # Install specific Chrome version (122.0.6261.111)
            wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_122.0.6261.111-1_amd64.deb
            sudo apt install -y ./google-chrome-stable_122.0.6261.111-1_amd64.deb

            # Get corresponding ChromeDriver
            DRIVER_VERSION=$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE_122)
            wget -O chromedriver.zip "https://chromedriver.storage.googleapis.com/${DRIVER_VERSION}/chromedriver_linux64.zip"
            unzip chromedriver.zip
            sudo mv chromedriver /usr/local/bin/
            sudo chmod +x /usr/local/bin/chromedriver

            # Log versions
            google-chrome --version
            chromedriver --version

      - run:
          name: Run RSpec
          command: bundle exec rspec

      - run:
          name: Run RuboCop
          command: bundle exec rubocop

  deploy:
    executor: default
    steps:
      - checkout
      - heroku/install
      - run:
          name: Deploy to Heroku
          command: |
            git remote add heroku https://git.heroku.com/runtime-movie.git || true
            git push heroku main -f

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build_test
      - deploy:
          requires:
            - build_test
          filters:
            branches:
              only: main
