version: 2.1

orbs:
  ruby: circleci/ruby@1.1.2
  heroku: circleci/heroku@1.2.6

jobs:
  test:
    docker:
      - image: cimg/ruby:3.2.2-browsers
    steps:
      - checkout

      - run:
          name: Check Chrome/Driver version
          command: |
            google-chrome --version
            chromedriver --version

      - run:
          name: Install dependencies
          command: bundle install --jobs=4 --retry=3

      - run:
          name: Setup DB
          command: |
            bundle exec rake db:create
            bundle exec rake db:schema:load

      - run:
          name: Run RuboCop
          command: bundle exec rubocop

      - run:
          name: Run RSpec
          command: bundle exec rspec

workflows:
  test-and-deploy:
    jobs:
      - test
      - heroku/deploy-via-git:
          app-name: "runtime-movie"
          branch: main
          requires:
            - test
          filters:
            branches:
              only: main
