version: 2.1

orbs:
  ruby: circleci/ruby@1.7.0
  node: circleci/node@4.1.0
  heroku: circleci/heroku@1.2.6

jobs:
  build_test:
    docker:
      - image: cimg/ruby:3.2.0
    working_directory: ~/app

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y libvips
            gem install bundler
            bundle install --jobs=4 --retry=3

      - node/install:
          node-version: '20.0.0'

      - run:
          name: Yarn install
          command: yarn install

      - run:
          name: Setup DB
          command: |
            cp config/database.yml.ci config/database.yml
            bundle exec rails db:create db:schema:load

      - run:
          name: Run RSpec
          command: bundle exec rspec

      - run:
          name: Run RuboCop
          command: bundle exec rubocop

  deploy:
    docker:
      - image: cimg/ruby:3.2.0
    steps:
      - checkout
      - heroku/install
      - run:
          name: Deploy to Heroku
          command: |
            git push https://heroku:${HEROKU_API_KEY}@git.heroku.com/runtime-movie.git main

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build_test
      - deploy:
          requires:
            - build_test
          filters:
            branches:
              only: main
