version: 2.1

orbs:
  ruby: circleci/ruby@1.1.2
  browser-tools: circleci/browser-tools@1.4.0
  heroku: circleci/heroku@1.2.6

jobs:
  test:
    docker:
      - image: cimg/ruby:3.2.2-browsers
    steps:
      - checkout

      - browser-tools/install-chrome

      - run:
          name: Install matching ChromeDriver
          command: |
            set -ex

            # Chromeのバージョン取得
            CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
            echo "Installed Chrome version: $CHROME_VERSION"

            # 対応するChromeDriverのバージョンを取得
            CHROMEDRIVER_VERSION=$(curl -s "https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json" \
              | jq -r --arg ver "$CHROME_VERSION" '.channels.Stable.version as $v | if $v | startswith($ver) then $v else empty end')

            if [ -z "$CHROMEDRIVER_VERSION" ]; then
              echo "No matching ChromeDriver version found for Chrome $CHROME_VERSION"
              exit 1
            fi

            echo "Matching ChromeDriver version: $CHROMEDRIVER_VERSION"

            # ChromeDriverをダウンロード
            curl -sSL "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/$CHROMEDRIVER_VERSION/linux64/chromedriver-linux64.zip" -o chromedriver.zip

            unzip chromedriver.zip
            chmod +x chromedriver-linux64/chromedriver
            sudo mv chromedriver-linux64/chromedriver /usr/local/bin/

      - run:
          name: Install dependencies
          command: bundle install --jobs=4 --retry=3

      - run:
          name: Set up DB
          command: |
            bundle exec rake db:create
            bundle exec rake db:schema:load

      - run:
          name: Run RuboCop
          command: bundle exec rubocop

      - run:
          name: Run RSpec tests
          command: bundle exec rspec

  deploy:
    docker:
      - image: cimg/ruby:3.2.2
    steps:
      - checkout

      - run:
          name: Install Heroku CLI
          command: |
            curl https://cli-assets.heroku.com/install.sh | sh

      - run:
          name: Deploy to Heroku
          command: |
            git remote add heroku https://git.heroku.com/runtime-movie.git
            echo | heroku auth:token
            git push heroku main -f

workflows:
  test-and-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: main
