version: 2.1

orbs:
  ruby: circleci/ruby@1.1.2
  browser-tools: circleci/browser-tools@1.4.0
  heroku: circleci/heroku@1.2.6

jobs:
  test:
    docker:
      - image: cimg/ruby:3.2.0-browsers  # Chrome & ChromeDriver含む
    steps:
      - browser-tools/install-chrome

      - run:
          name: Install matching ChromeDriver
          command: |
            set -ex
            sudo apt-get update && sudo apt-get install -y unzip
            CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+\.\d+')
            echo "Installed Chrome version: $CHROME_VERSION"
            CHROMEDRIVER_URL="https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/$CHROME_VERSION/linux64/chromedriver-linux64.zip"
            echo "Downloading ChromeDriver from: $CHROMEDRIVER_URL"
            curl -sSL "$CHROMEDRIVER_URL" -o chromedriver.zip
            unzip chromedriver.zip
            chmod +x chromedriver-linux64/chromedriver
            sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
            rm -rf chromedriver.zip chromedriver-linux64

      - checkout

      - browser-tools/install-chrome

      - run:
          name: Install matching ChromeDriver
          command: |
            set -ex
            sudo apt-get update && sudo apt-get install -y unzip
            CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+\.\d+')
            echo "Installed Chrome version: $CHROME_VERSION"
            CHROMEDRIVER_URL="https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/$CHROME_VERSION/linux64/chromedriver-linux64.zip"
            echo "Downloading ChromeDriver from: $CHROMEDRIVER_URL"
            curl -sSL "$CHROMEDRIVER_URL" -o chromedriver.zip
            unzip chromedriver.zip
            chmod +x chromedriver-linux64/chromedriver
            sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
            rm -rf chromedriver.zip chromedriver-linux64

      - run:
          name: Install dependencies
          command: bundle install --jobs=4 --retry=3

      - run:
          name: Set up DB
          command: |
            bundle exec rake db:create
            bundle exec rake db:schema:load

      - run:
          name: Run RuboCop
          command: bundle exec rubocop

      - run:
          name: Webpacker compile
          command: bundle exec rails webpacker:compile RAILS_ENV=test

      - run:
          name: Run RSpec tests
          command: bundle exec rspec

  deploy:
    docker:
      - image: cimg/ruby:3.2.2
    steps:
      - checkout

      - run:
          name: Install Heroku CLI
          command: |
            curl https://cli-assets.heroku.com/install.sh | sh

      - run:
          name: Deploy to Heroku
          command: |
            git remote add heroku https://git.heroku.com/runtime-movie.git
            echo | heroku auth:token
            git push heroku main -f

workflows:
  test-and-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: main
