version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6

executors:
  default:
    docker:
      - image: cimg/ruby:3.2.0-node
    working_directory: ~/app

jobs:
  build_test:
    docker:
      - image: cimg/ruby:3.2.0-node
      - image: cimg/postgres:14.9
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: app_test
          POSTGRES_PASSWORD: password
    steps:
      - checkout

      - run:
          name: Install system dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y \
              curl unzip wget gnupg2 libasound2 libatk-bridge2.0-0 libgtk-3-0 \
              libxss1 libnss3 libx11-xcb1 xdg-utils fonts-liberation \
              libappindicator3-1

      - run:
          name: Install latest Chrome
          command: |
            curl -sSL https://dl.google.com/linux/linux_signing_key.pub | sudo gpg --dearmor -o /usr/share/keyrings/google-linux.gpg
            echo "deb [arch=amd64 signed-by=/usr/share/keyrings/google-linux.gpg] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
            sudo apt-get update
            sudo apt-get install -y google-chrome-stable
            google-chrome --version

      - run:
          name: Install matching ChromeDriver
          command: |
            CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
            DRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
            wget -O chromedriver.zip "https://chromedriver.storage.googleapis.com/${DRIVER_VERSION}/chromedriver_linux64.zip"
            unzip chromedriver.zip
            sudo mv chromedriver /usr/local/bin/
            sudo chmod +x /usr/local/bin/chromedriver
            chromedriver --version

      - run:
          name: Install Ruby gems
          command: |
            gem install bundler
            bundle install --jobs=4 --retry=3

      - run:
          name: Yarn install
          command: yarn install --check-files

      - run:
          name: Setup DB
          command: |
            cp config/database.yml.ci config/database.yml || echo "No DB override"
            bundle exec rails db:create db:schema:load

      - run:
          name: Run RSpec
          command: bundle exec rspec

      - run:
          name: Run RuboCop
          command: bundle exec rubocop

  deploy:
    executor: default
    steps:
      - checkout
      - heroku/install
      - run:
          name: Deploy to Heroku
          command: |
            git remote add heroku https://git.heroku.com/runtime-movie.git || true
            git push heroku main -f

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build_test
      - deploy:
          requires:
            - build_test
          filters:
            branches:
              only: main
